apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-symptom-checker-deployment
  labels:
    app: ai-symptom-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-symptom-checker
  template:
    metadata:
      labels:
        app: ai-symptom-checker
    spec:
      containers:
        - name: ai-symptom-checker
          image: ai-symptom-checker-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5005
          env:
            - name: GEMINI_API_KEY
              value: "AIzaSyDn0XzdNCuFwP5j2UoQ1QxjQI65uGAipSE"
            - name: GEMINI_MODEL
              value: "gemini-2.5-flash"
