apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service-deployment
  labels:
    app: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: appointment-service-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: appointment-service-secrets
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: appointment-service-secrets
                  key: JWT_SECRET
            - name: CORS_ORIGIN
              value: "http://smart-healthcare.local"
            - name: PORT
              value: "5003"
            - name: AUTH_SERVICE_BASE_URL
              value: "http://auth-service:5001/api"
            - name: PATIENT_SERVICE_BASE_URL
              value: "http://patient-service:5002/api"
            - name: NOTIFICATION_API_URL
              value: "http://notification-service:5007/api/notifications/send"
            - name: TELEMEDICINE_API_URL
              value: "http://telemedicine-service:5008/api/telemedicine"
