apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service-deployment
  labels:
    app: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: appointment-service-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: appointment-service-secrets
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: appointment-service-secrets
                  key: JWT_SECRET
            - name: CORS_ORIGIN
              value: "http://smart-healthcare.local"
            - name: PORT
              value: "5003"
