apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
type: Opaque
stringData:
  MONGODB_URI: "replace-with-auth-mongodb-uri"
  JWT_SECRET: "replace-with-auth-jwt-secret"
  JWT_EXPIRES_IN: "1d"
  JWT_EXPIRES_IN: "7d"
