apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service-deployment
  labels:
    app: doctor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
        - name: doctor-service
          image: doctor-service-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5003
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: doctor-service-secrets
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: JWT_SECRET
            - name: CORS_ORIGIN
              value: "http://smart-healthcare.local"
            - name: PORT
              value: "5003"
