apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5007
          env:
            - name: EMAIL_USER
              value: "webstorebs@gmail.com"
            - name: EMAIL_APP_PASSWORD
              value: "xoyx xfiu xetd ofzs"
