apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5007
          env:
            - name: NODE_OPTIONS
              value: "--dns-result-order=ipv4first"
            - name: EMAIL_PROVIDER
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: EMAIL_PROVIDER
                  optional: true
            - name: EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: EMAIL_FROM
                  optional: true
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: SENDGRID_API_KEY
                  optional: true
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: TWILIO_ACCOUNT_SID
                  optional: true
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: TWILIO_AUTH_TOKEN
                  optional: true
            - name: TWILIO_PHONE_NUMBER
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: TWILIO_PHONE_NUMBER
                  optional: true
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: EMAIL_USER
            - name: EMAIL_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: EMAIL_APP_PASSWORD
