apiVersion: v1
kind: Secret
metadata:
  name: patient-service-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://dbuser:Binoth123456@cluster0.udtxha2.mongodb.net/patient_db?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET: "change-this-to-a-long-random-secret-value"
